apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: zipkin
config: 
  local_service_name: kong
  http_endpoint: http://zipkin:9411/api/v2/spans
  sample_ratio: 1
  include_credential: true
  traceid_byte_count: 16
  header_type: preserve
  default_header_type: b3
  tags_header: Zipkin-Tags
  default_service_name: kong
plugin: zipkin